---
title: "Seawater Standard rec 127299"
author: "BEL"
date: "04/17/2015"
output: html_document
---

Determination of mean fm and error for Seawater standard rec num 127299.

Data pulled from no_os by rec_num.
```{r echo=FALSE, message=FALSE}
#Load Libraries
library(amstools)
library(ggplot2)
library(dplyr)
library(knitr)

digits=4

#set parameters- from, to, sys not used if loading from file
from <- '2014-09-01'
to <- 'present' #present or date
sys <- 'both' #cfams, usams, ams1 or both

#Pull the data
ss <- getStandards(from, to, sys, rec = 124646)
```

Here's the data...

```{r, echo=FALSE, message=FALSE}
ss <- mutate(ss, system = substring(wheel, 1, 5))
qplot(f_modern, data=ss) + facet_grid(system ~ .)

ss <- filter(ss, f_modern > 0, f_modern < 0.008)
kable(select(ss, tp_num, tp_date_pressed, gf_co2_qty, f_modern, f_int_error, f_ext_error))

sum <- ss %>% 
  select(tp_num, tp_date_pressed, system, gf_co2_qty, f_modern, f_int_error, f_ext_error) %>%
  group_by(system) %>%
  summarize(fm = mean(f_modern), sd = sd(f_modern), err = mean(pmax(f_int_error, f_ext_error)), N = n())

kable(sum)
```

That leaves us with N = `r nrow(ss)`, mean = `r mean(ss$f_modern)`, sd = `r sd(ss$f_modern)`.

